# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/shrey/Desktop/AES_SV/.Xil/Vivado-20044-Shrey-Zenbook/incrSyn
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a200tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/shrey/Desktop/AES_SV/AES_SV.cache/wt [current_project]
set_property parent.project_path C:/Users/shrey/Desktop/AES_SV/AES_SV.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/shrey/Desktop/AES_SV/AES_SV.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/shrey/Desktop/AES_SV/AES_SV.srcs/sources_1/new/key_expansion.v
  C:/Users/shrey/Desktop/AES_SV/AES_SV.srcs/sources_1/new/mixcolumn.v
  C:/Users/shrey/Desktop/AES_SV/AES_SV.srcs/sources_1/new/mul11_lut.v
  C:/Users/shrey/Desktop/AES_SV/AES_SV.srcs/sources_1/new/mul13_lut.v
  C:/Users/shrey/Desktop/AES_SV/AES_SV.srcs/sources_1/new/mul14_lut.v
  C:/Users/shrey/Desktop/AES_SV/AES_SV.srcs/sources_1/new/mul2_lut.v
  C:/Users/shrey/Desktop/AES_SV/AES_SV.srcs/sources_1/new/mul3_lut.v
  C:/Users/shrey/Desktop/AES_SV/AES_SV.srcs/sources_1/new/mul9_lut.v
  C:/Users/shrey/Desktop/AES_SV/AES_SV.srcs/sources_1/new/rounds.v
  C:/Users/shrey/Desktop/AES_SV/AES_SV.srcs/sources_1/new/sbox.v
  C:/Users/shrey/Desktop/AES_SV/AES_SV.srcs/sources_1/new/shiftrow.v
  C:/Users/shrey/Desktop/AES_SV/AES_SV.srcs/sources_1/new/subbytes.v
  C:/Users/shrey/Desktop/AES_SV/AES_SV.srcs/sources_1/new/aes_main.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top aes_main -part xc7a200tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef aes_main.dcp
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
